// react-component-by-vite/src/Counter.tsx
import {useEffect, useState} from "react";

export const Counter = () => {
    const [count, setCount] = useState(0);

    console.log("Component by vite render");

    useEffect(() => {
        console.log("Component by vite mounted");
        // window.xxx3 = React
    }, []);

    return (
        <div style={{
            backgroundColor: "rgba(25, 230, 40, 0.4)",
            color: "white",
            padding: 20
        }}>
            <div>This is counter react by Vite</div>
            <div>Count = {count}</div>
            <button onClick={() => setCount(count + 1)}>Add One</button>
        </div>
    );
};

export default Counter;

// solid-component/src/Counter.jsx
import {createSignal} from "solid-js";

export default () => {
    const [count, setCount] = createSignal(0);

    return (
        <div class="bg-blue-600 text-white p-5">
            <div>This is counter solid</div>
            <div>Count = {count()}</div>
            <button onClick={() => setCount(count() + 1)}>Add One</button>
        </div>
    );
};
